#!/bin/sh
#
# Symlink this hook to .git/hooks/pre-commit for it to work as a pre-commit hook.

FILES=$(git diff-index --cached HEAD | cut -f2 )
JSFILES=$(printf '%s\n' $FILES | grep '\.js$')
PRETTIERFILES=$(printf '%s\n' $FILES | grep '\.\(css\|html\|js\|json\|less\|md\|scss\|yaml\|yml\)$')
TESTJSFILES=$(printf '%s\n' $FILES | grep '\.test\.js$')
echo $PRETTIERFILES

npx=$(which npx)
if dart w; then
    npx="dart x - npx"
fi

exit=0

if test "$PRETTIERFILES"; then
    if ! $npx prettierx --check $PRETTIERFILES > /dev/null; then
        $npx prettierx  --write $PRETTIERFILES
        $npx prettierx  --check $PRETTIERFILES
        # Make sure a message goes out about needing to stage changes.
        test $? -eq 0 && echo "Please stage changes made by prettier."
        exit=1
    fi
fi

if test "$JSFILES"; then
    if ! $npx semistandard $JSFILES > /dev/null; then
        $npx semistandard --fix $JSFILES
        $npx semistandard -v $JSFILES
        # Print a message if this one didn't print anything.
        test $? -eq 0 && echo "Please stage changes made by semistandard."
        exit=1
    fi
fi

if test "$TESTJSFILES"; then
    $npx jest $TESTJSFILES
    test $? -eq 0 || exit=1
fi

exit $exit
