.test_template: &test_definition
  stage: test
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: 'normal'
  script:
    - node --version
    - npm install
    - npm run style:check
    - npm run test -- --collectCoverage
    - npm run compile

testnode10:
  image: node:10
  <<: *test_definition
  cache:
    key: node10
    paths:
      - node_modules

testnode12:
  image: node:12
  <<: *test_definition
  artifacts:
    paths:
      - coverage/
    expire_in: 1 day
  cache:
    key: node12
    paths:
      - node_modules

docs:
  stage: deploy
  tags:
    - static-server
  dependencies:
    - testnode12
  script:
    - rm -rf ~static/coverage/dynamic-presentation
    - mv coverage/lcov-report ~static/coverage/dynamic-presentation
  only:
    - master
