version: '2.2'

services:
  web:
    image: node:10
    ports:
      - ${WEB_PORT}:8080
    volumes:
      - ..:/var/www/
    command: 'npm --allow-root --unsafe-perm=true run setupAndServe'
    working_dir: /var/www
    restart: always
